### ISSUE TITLE
Using of plugin

### ISSUE THREAD

**Issue by ghost** [kiklop74/moodle-local_dompdf#1]
Hi,
i used DOMPDF before, but i implemeted it into my plugin,
i have problem now, because im using it to export documents to PDF and i am using images from FILE API of moodle. 

Can you describe how to use your local plugin?

**Comment by kiklop74** [comment]
I just added clarification to the Readme and one example. Look into new examples directory.
With regards to images I will look into adding that.

**Comment by kiklop74** [comment]
I just added support for images and an example for that in README file.

**Comment by kiklop74** [comment]
Done

**Comment by lukascelinak** [comment]
Hi, i found one issue, when im using images in editor with spaces in name, DOMPDF is not loading them, for example:
test.png is ok, test with spaces.png no.
