### ISSUE TITLE
Moodle plugin CSS is not loading

### ISSUE THREAD

**Issue by lukascelinak** [kiklop74/moodle-local_dompdf#2]
Hi, 
i have used your plugin in my plugins for export document into pdf, im trying to update local_dompdf but i found a bug, old version with dompdf <75f13c70> was working fine, but new version of plugin with new dompdf library does not work well, the plugin is not loading css file using <link rel="stylesheet" ref="{$CFG->wwwroot}/mod/printit/styles.css">, in previous version wasnt problem with this. 

I tried relative path, absolute path and nothing helped. 
Thank for help how to solve this problem.

**Comment by kiklop74** [comment]
Can you provide a code example so that I can check it out?

**Comment by lukascelinak** [comment]
Hi Darko, i added you to my private repo. Thanks for help.

**Comment by kiklop74** [comment]
Your problem can most likely be resolved with code as below:

```php
use Dompdf\Options;

$pdf = \local_dompdf\api\pdf::createnew();
$options = new Options();
$options->setChroot(['fullpath1', 'fullpath2', 'fullpath3']);
$pdf->setOptions($options);
// Other code
```
You need to add full path to directory or directories where linked external files are to be expected. So if you have your plugin located in `[Moodlepath]/mod/myplugin` and in there you have style.css that needs to be loaded than that path needs to be added.

**Comment by lukascelinak** [comment]
Thank you.

**Comment by kiklop74** [comment]
If the solution works please close the issue.
