### ISSUE TITLE
 file_rewrite_image_urls() does not work with overridden images in html editor #3216 

### ISSUE THREAD

**Issue by lukascelinak** [kiklop74/moodle-local_dompdf#3]
I found bug, where function for rewrite images does not work with in html editor overridden files.
Moodle is putting atribute time after image url, when are you overriding files in html editor, then rewrite function is giving back not rewritten image src path.

Uploaded and overridden file url:
/draftfile.php/5/user/draft/838522161/image.jpg?time=1685103678494

Stored file url:
@@PluginFile@@/image.jpg?time=1685103678494

Rewritten file url:
@@PluginFile@@/image.jpg?time=1685103678494

Standard moodle images rewrite function file_rewrite_pluginfile_urls() is working for this rewrite.

**Comment by kiklop74** [comment]
Thanks for the fix.
